"""Test fixtures for mtg-json-tools tests."""

from __future__ import annotations

import pytest

from mtg_json_tools import MtgJsonTools
from mtg_json_tools.cache import CacheManager
from mtg_json_tools.connection import Connection

# === Sample data ===

SAMPLE_CARDS = [
    {
        "uuid": "card-uuid-001",
        "name": "Lightning Bolt",
        "asciiName": "Lightning Bolt",
        "faceName": None,
        "type": "Instant",
        "types": ["Instant"],
        "subtypes": [],
        "supertypes": [],
        "colors": ["R"],
        "colorIdentity": ["R"],
        "colorIndicator": None,
        "producedMana": None,
        "manaCost": "{R}",
        "text": "Lightning Bolt deals 3 damage to any target.",
        "layout": "normal",
        "side": None,
        "power": None,
        "toughness": None,
        "loyalty": None,
        "keywords": None,
        "identifiers": {},
        "isFunny": None,
        "edhrecSaltiness": None,
        "subsets": None,
        "convertedManaCost": 1.0,
        "manaValue": 1.0,
        "faceConvertedManaCost": None,
        "faceManaValue": None,
        "defense": None,
        "hand": None,
        "life": None,
        "edhrecRank": 5,
        "legalities": {},
        "leadershipSkills": None,
        "rulings": None,
        "hasAlternativeDeckLimit": None,
        "isReserved": None,
        "isGameChanger": None,
        "printings": ["A25", "2ED", "3ED", "M10", "M11"],
        "purchaseUrls": {},
        "relatedCards": None,
        "setCode": "A25",
        "number": "141",
        "artist": "Christopher Moeller",
        "artistIds": None,
        "borderColor": "black",
        "frameVersion": "2015",
        "frameEffects": None,
        "watermark": None,
        "signature": None,
        "securityStamp": None,
        "flavorText": None,
        "flavorName": None,
        "faceFlavorName": None,
        "originalText": "Lightning Bolt deals 3 damage to any target.",
        "originalType": "Instant",
        "printedName": None,
        "printedText": None,
        "printedType": None,
        "facePrintedName": None,
        "availability": ["paper", "mtgo"],
        "boosterTypes": None,
        "finishes": ["nonfoil", "foil"],
        "promoTypes": None,
        "attractionLights": None,
        "isFullArt": None,
        "isOnlineOnly": None,
        "isOversized": None,
        "isPromo": None,
        "isReprint": True,
        "isTextless": None,
        "otherFaceIds": None,
        "cardParts": None,
        "language": "English",
        "sourceProducts": None,
        "rarity": "uncommon",
        "duelDeck": None,
        "isRebalanced": None,
        "originalPrintings": None,
        "rebalancedPrintings": None,
        "originalReleaseDate": None,
        "isAlternative": None,
        "isStorySpotlight": None,
        "isTimeshifted": None,
        "hasContentWarning": None,
        "variations": None,
        "foreignData": None,
        "releaseDate": "2018-03-16",
    },
    {
        "uuid": "card-uuid-002",
        "name": "Counterspell",
        "asciiName": "Counterspell",
        "faceName": None,
        "type": "Instant",
        "types": ["Instant"],
        "subtypes": [],
        "supertypes": [],
        "colors": ["U"],
        "colorIdentity": ["U"],
        "colorIndicator": None,
        "producedMana": None,
        "manaCost": "{U}{U}",
        "text": "Counter target spell.",
        "layout": "normal",
        "side": None,
        "power": None,
        "toughness": None,
        "loyalty": None,
        "keywords": None,
        "identifiers": {},
        "isFunny": None,
        "edhrecSaltiness": 1.5,
        "subsets": None,
        "convertedManaCost": 2.0,
        "manaValue": 2.0,
        "faceConvertedManaCost": None,
        "faceManaValue": None,
        "defense": None,
        "hand": None,
        "life": None,
        "edhrecRank": 10,
        "legalities": {},
        "leadershipSkills": None,
        "rulings": None,
        "hasAlternativeDeckLimit": None,
        "isReserved": None,
        "isGameChanger": None,
        "printings": ["MH2", "A25"],
        "purchaseUrls": {},
        "relatedCards": None,
        "setCode": "MH2",
        "number": "267",
        "artist": "Zack Stella",
        "artistIds": None,
        "borderColor": "black",
        "frameVersion": "2015",
        "frameEffects": None,
        "watermark": None,
        "signature": None,
        "securityStamp": None,
        "flavorText": None,
        "flavorName": None,
        "faceFlavorName": None,
        "originalText": "Counter target spell.",
        "originalType": "Instant",
        "printedName": None,
        "printedText": None,
        "printedType": None,
        "facePrintedName": None,
        "availability": ["paper", "mtgo"],
        "boosterTypes": None,
        "finishes": ["nonfoil", "foil"],
        "promoTypes": None,
        "attractionLights": None,
        "isFullArt": None,
        "isOnlineOnly": None,
        "isOversized": None,
        "isPromo": None,
        "isReprint": True,
        "isTextless": None,
        "otherFaceIds": None,
        "cardParts": None,
        "language": "English",
        "sourceProducts": None,
        "rarity": "uncommon",
        "duelDeck": None,
        "isRebalanced": None,
        "originalPrintings": None,
        "rebalancedPrintings": None,
        "originalReleaseDate": None,
        "isAlternative": None,
        "isStorySpotlight": None,
        "isTimeshifted": None,
        "hasContentWarning": None,
        "variations": None,
        "foreignData": None,
        "releaseDate": "2021-06-18",
    },
    {
        "uuid": "card-uuid-003",
        "name": "Fire // Ice",
        "asciiName": "Fire // Ice",
        "faceName": "Fire",
        "type": "Instant",
        "types": ["Instant"],
        "subtypes": [],
        "supertypes": [],
        "colors": ["R"],
        "colorIdentity": ["R", "U"],
        "colorIndicator": None,
        "producedMana": None,
        "manaCost": "{1}{R}",
        "text": "Fire deals 2 damage divided as you choose among one or two targets.",
        "layout": "split",
        "side": "a",
        "power": None,
        "toughness": None,
        "loyalty": None,
        "keywords": None,
        "identifiers": {},
        "isFunny": None,
        "edhrecSaltiness": None,
        "subsets": None,
        "convertedManaCost": 4.0,
        "manaValue": 4.0,
        "faceConvertedManaCost": 2.0,
        "faceManaValue": 2.0,
        "defense": None,
        "hand": None,
        "life": None,
        "edhrecRank": 100,
        "legalities": {},
        "leadershipSkills": None,
        "rulings": None,
        "hasAlternativeDeckLimit": None,
        "isReserved": None,
        "isGameChanger": None,
        "printings": ["A25"],
        "purchaseUrls": {},
        "relatedCards": None,
        "setCode": "A25",
        "number": "223a",
        "artist": "Dan Scott",
        "artistIds": None,
        "borderColor": "black",
        "frameVersion": "2015",
        "frameEffects": None,
        "watermark": None,
        "signature": None,
        "securityStamp": None,
        "flavorText": None,
        "flavorName": None,
        "faceFlavorName": None,
        "originalText": None,
        "originalType": None,
        "printedName": None,
        "printedText": None,
        "printedType": None,
        "facePrintedName": None,
        "availability": ["paper", "mtgo"],
        "boosterTypes": None,
        "finishes": ["nonfoil"],
        "promoTypes": None,
        "attractionLights": None,
        "isFullArt": None,
        "isOnlineOnly": None,
        "isOversized": None,
        "isPromo": None,
        "isReprint": True,
        "isTextless": None,
        "otherFaceIds": ["card-uuid-004"],
        "cardParts": None,
        "language": "English",
        "sourceProducts": None,
        "rarity": "uncommon",
        "duelDeck": None,
        "isRebalanced": None,
        "originalPrintings": None,
        "rebalancedPrintings": None,
        "originalReleaseDate": None,
        "isAlternative": None,
        "isStorySpotlight": None,
        "isTimeshifted": None,
        "hasContentWarning": None,
        "variations": None,
        "foreignData": None,
        "releaseDate": "2018-03-16",
    },
]

SAMPLE_SETS = [
    {
        "code": "A25",
        "name": "Masters 25",
        "type": "masters",
        "releaseDate": "2018-03-16",
        "baseSetSize": 249,
        "totalSetSize": 249,
        "keyruneCode": "A25",
        "translations": {},
        "block": None,
        "parentCode": None,
        "mtgoCode": "A25",
        "tokenSetCode": None,
        "mcmId": None,
        "mcmIdExtras": None,
        "mcmName": None,
        "tcgplayerGroupId": None,
        "cardsphereSetId": None,
        "isFoilOnly": False,
        "isNonFoilOnly": None,
        "isOnlineOnly": False,
        "isPaperOnly": None,
        "isForeignOnly": None,
        "isPartialPreview": None,
        "languages": ["English"],
        "sealedProduct": [
            {
                "uuid": "sealed-uuid-001",
                "name": "Masters 25 Booster Box",
                "category": "booster_box",
                "subtype": None,
                "purchaseUrls": {},
                "releaseDate": "2018-03-16",
            },
            {
                "uuid": "sealed-uuid-002",
                "name": "Masters 25 Booster Pack",
                "category": "booster_pack",
                "subtype": None,
                "purchaseUrls": {},
                "releaseDate": "2018-03-16",
            },
        ],
        "booster": None,
    },
    {
        "code": "MH2",
        "name": "Modern Horizons 2",
        "type": "draft_innovation",
        "releaseDate": "2021-06-18",
        "baseSetSize": 303,
        "totalSetSize": 531,
        "keyruneCode": "MH2",
        "translations": {},
        "block": None,
        "parentCode": None,
        "mtgoCode": "MH2",
        "tokenSetCode": None,
        "mcmId": None,
        "mcmIdExtras": None,
        "mcmName": None,
        "tcgplayerGroupId": None,
        "cardsphereSetId": None,
        "isFoilOnly": False,
        "isNonFoilOnly": None,
        "isOnlineOnly": False,
        "isPaperOnly": None,
        "isForeignOnly": None,
        "isPartialPreview": None,
        "languages": ["English"],
        "sealedProduct": [
            {
                "uuid": "sealed-uuid-003",
                "name": "MH2 Set Booster Box",
                "category": "booster_box",
                "subtype": None,
                "purchaseUrls": {},
                "releaseDate": "2021-06-18",
            },
        ],
        "booster": None,
    },
]

SAMPLE_TOKENS = [
    {
        "uuid": "token-uuid-001",
        "name": "Soldier Token",
        "asciiName": "Soldier Token",
        "faceName": None,
        "type": "Token Creature — Soldier",
        "types": ["Token", "Creature"],
        "subtypes": ["Soldier"],
        "supertypes": [],
        "colors": ["W"],
        "colorIdentity": ["W"],
        "colorIndicator": None,
        "producedMana": None,
        "manaCost": None,
        "text": None,
        "layout": "token",
        "side": None,
        "power": "1",
        "toughness": "1",
        "loyalty": None,
        "keywords": None,
        "identifiers": {},
        "setCode": "A25",
        "number": "T1",
        "artist": "Zack Stella",
        "artistIds": None,
        "borderColor": "black",
        "frameVersion": "2015",
        "frameEffects": None,
        "watermark": None,
        "signature": None,
        "securityStamp": None,
        "flavorText": None,
        "flavorName": None,
        "availability": ["paper"],
        "finishes": ["nonfoil"],
        "promoTypes": None,
        "isFullArt": None,
        "isOnlineOnly": None,
        "isPromo": None,
        "isReprint": None,
        "isTextless": None,
        "language": "English",
        "releaseDate": "2018-03-16",
        "reverseRelated": None,
        "relatedCards": None,
    },
    {
        "uuid": "token-uuid-002",
        "name": "Beast Token",
        "asciiName": "Beast Token",
        "faceName": None,
        "type": "Token Creature — Beast",
        "types": ["Token", "Creature"],
        "subtypes": ["Beast"],
        "supertypes": [],
        "colors": ["G"],
        "colorIdentity": ["G"],
        "colorIndicator": None,
        "producedMana": None,
        "manaCost": None,
        "text": None,
        "layout": "token",
        "side": None,
        "power": "3",
        "toughness": "3",
        "loyalty": None,
        "keywords": None,
        "identifiers": {},
        "setCode": "MH2",
        "number": "T2",
        "artist": "Jason Rainville",
        "artistIds": None,
        "borderColor": "black",
        "frameVersion": "2015",
        "frameEffects": None,
        "watermark": None,
        "signature": None,
        "securityStamp": None,
        "flavorText": None,
        "flavorName": None,
        "availability": ["paper"],
        "finishes": ["nonfoil"],
        "promoTypes": None,
        "isFullArt": None,
        "isOnlineOnly": None,
        "isPromo": None,
        "isReprint": None,
        "isTextless": None,
        "language": "English",
        "releaseDate": "2021-06-18",
        "reverseRelated": None,
        "relatedCards": None,
    },
]

SAMPLE_IDENTIFIERS = [
    {
        "uuid": "card-uuid-001",
        "scryfallId": "scryfall-001",
        "scryfallOracleId": "oracle-001",
        "scryfallIllustrationId": "illust-001",
        "tcgplayerProductId": "12345",
        "tcgplayerEtchedProductId": None,
        "mtgoId": "mtgo-001",
        "mtgoFoilId": "mtgo-foil-001",
        "mtgArenaId": "arena-001",
        "multiverseId": "442130",
        "mcmId": "mcm-001",
        "mcmMetaId": "mcm-meta-001",
        "cardKingdomId": "ck-001",
        "cardKingdomFoilId": "ck-foil-001",
        "cardKingdomEtchedId": None,
        "cardsphereId": "cs-001",
        "cardsphereFoilId": "cs-foil-001",
    },
    {
        "uuid": "card-uuid-002",
        "scryfallId": "scryfall-002",
        "scryfallOracleId": "oracle-002",
        "scryfallIllustrationId": "illust-002",
        "tcgplayerProductId": "67890",
        "tcgplayerEtchedProductId": None,
        "mtgoId": "mtgo-002",
        "mtgoFoilId": None,
        "mtgArenaId": "arena-002",
        "multiverseId": "522205",
        "mcmId": "mcm-002",
        "mcmMetaId": None,
        "cardKingdomId": "ck-002",
        "cardKingdomFoilId": None,
        "cardKingdomEtchedId": None,
        "cardsphereId": None,
        "cardsphereFoilId": None,
    },
]

SAMPLE_FOREIGN_DATA = [
    {
        "uuid": "card-uuid-001",
        "name": "Blitzschlag",
        "language": "German",
        "text": "Der Blitzschlag fügt einem Ziel deiner Wahl 3 Schadenspunkte zu.",
        "type": "Spontanzauber",
        "faceName": None,
        "flavorText": None,
        "multiverseId": None,
    },
    {
        "uuid": "card-uuid-001",
        "name": "Foudre",
        "language": "French",
        "text": "La Foudre inflige 3 blessures à n'importe quelle cible.",
        "type": "Éphémère",
        "faceName": None,
        "flavorText": None,
        "multiverseId": None,
    },
    {
        "uuid": "card-uuid-002",
        "name": "Contresort",
        "language": "French",
        "text": "Contrecarrez le sort ciblé.",
        "type": "Éphémère",
        "faceName": None,
        "flavorText": None,
        "multiverseId": None,
    },
]

SAMPLE_LEGALITIES = [
    {"uuid": "card-uuid-001", "format": "modern", "status": "Legal"},
    {"uuid": "card-uuid-001", "format": "legacy", "status": "Legal"},
    {"uuid": "card-uuid-001", "format": "vintage", "status": "Restricted"},
    {"uuid": "card-uuid-001", "format": "standard", "status": "Not Legal"},
    {"uuid": "card-uuid-002", "format": "modern", "status": "Legal"},
    {"uuid": "card-uuid-002", "format": "legacy", "status": "Legal"},
    {"uuid": "card-uuid-002", "format": "vintage", "status": "Legal"},
    {"uuid": "card-uuid-002", "format": "standard", "status": "Not Legal"},
    {"uuid": "card-uuid-002", "format": "historic", "status": "Suspended"},
]


@pytest.fixture
def tmp_cache(tmp_path):
    """Provide a temporary cache directory."""
    return tmp_path / "cache"


@pytest.fixture
def sample_db(tmp_path):
    """Create a DuckDB with sample data (no network calls needed)."""
    cache = CacheManager(tmp_path / "cache", offline=True)
    conn = Connection(cache)

    # Register sample data directly as tables
    conn.register_table_from_data("cards", SAMPLE_CARDS)
    conn.register_table_from_data("sets", SAMPLE_SETS)
    conn.register_table_from_data("tokens", SAMPLE_TOKENS)
    conn.register_table_from_data("card_identifiers", SAMPLE_IDENTIFIERS)
    conn.register_table_from_data("card_legalities", SAMPLE_LEGALITIES)
    conn.register_table_from_data("card_foreign_data", SAMPLE_FOREIGN_DATA)

    yield conn

    conn.close()
    cache.close()


@pytest.fixture
def sdk_offline(tmp_path):
    """SDK instance with sample data loaded (no network)."""
    sdk = MtgJsonTools(cache_dir=tmp_path / "cache", offline=True)

    # Load sample data directly
    sdk._conn.register_table_from_data("cards", SAMPLE_CARDS)
    sdk._conn.register_table_from_data("sets", SAMPLE_SETS)
    sdk._conn.register_table_from_data("tokens", SAMPLE_TOKENS)
    sdk._conn.register_table_from_data("card_identifiers", SAMPLE_IDENTIFIERS)
    sdk._conn.register_table_from_data("card_legalities", SAMPLE_LEGALITIES)
    sdk._conn.register_table_from_data("card_foreign_data", SAMPLE_FOREIGN_DATA)

    yield sdk

    sdk.close()
