"""Vendored MTGJSON Pydantic models (standalone, no build-pipeline dependencies)."""

from .cards import (
    CardAtomic,
    CardBase,
    CardDeck,
    CardSet,
    CardSetDeck,
    CardToken,
)
from .decks import Deck, DeckList
from .sealed import SealedProduct
from .sets import DeckSet, MtgSet, SetList
from .submodels import (
    BoosterConfig,
    BoosterPack,
    BoosterSheet,
    CardType,
    CardTypes,
    ForeignData,
    Identifiers,
    Keywords,
    LeadershipSkills,
    Legalities,
    Meta,
    PriceFormats,
    PriceList,
    PricePoints,
    PurchaseUrls,
    RelatedCards,
    Rulings,
    SealedProductContents,
    SourceProducts,
    TcgplayerSkus,
    Translations,
)

__all__ = [
    "BoosterConfig",
    "BoosterPack",
    "BoosterSheet",
    "CardAtomic",
    "CardBase",
    "CardDeck",
    "CardSet",
    "CardSetDeck",
    "CardToken",
    "CardType",
    "CardTypes",
    "Deck",
    "DeckList",
    "DeckSet",
    "ForeignData",
    "Identifiers",
    "Keywords",
    "LeadershipSkills",
    "Legalities",
    "Meta",
    "MtgSet",
    "PriceFormats",
    "PriceList",
    "PricePoints",
    "PurchaseUrls",
    "RelatedCards",
    "Rulings",
    "SealedProduct",
    "SealedProductContents",
    "SetList",
    "SourceProducts",
    "TcgplayerSkus",
    "Translations",
]
