"""MTGJSON card models (vendored, standalone)."""

from __future__ import annotations

import json as _json
from typing import Any

from pydantic import BaseModel, Field, model_validator

from .submodels import (
    ForeignData,
    Identifiers,
    LeadershipSkills,
    Legalities,
    PurchaseUrls,
    RelatedCards,
    Rulings,
    SourceProducts,
)

# Fields that may be JSON strings in flat parquet but should be dicts/lists
_JSON_STRING_FIELDS = frozenset(
    {
        "identifiers",
        "legalities",
        "leadershipSkills",
        "purchaseUrls",
        "relatedCards",
        "sourceProducts",
        "rulings",
        "foreignData",
    }
)


def _parse_json_value(v: Any) -> Any:
    """Convert JSON strings to Python objects, empty/null to None."""
    if v is None:
        return None
    if isinstance(v, str):
        stripped = v.strip()
        if not stripped:
            return None
        try:
            return _json.loads(stripped)
        except (ValueError, _json.JSONDecodeError):
            return None
    return v


class CardBase(BaseModel):
    """Base fields shared by all card types."""

    model_config = {"populate_by_name": True}

    @model_validator(mode="before")
    @classmethod
    def _preprocess_json_strings(cls, data: Any) -> Any:
        """Parse JSON string fields from flat parquet into dicts/lists."""
        if isinstance(data, dict):
            for key in _JSON_STRING_FIELDS:
                if key in data and isinstance(data[key], str):
                    parsed = _parse_json_value(data[key])
                    data[key] = parsed if parsed is not None else {}
        return data

    name: str = Field(description="The name of the card.")
    ascii_name: str | None = Field(default=None, alias="asciiName")
    face_name: str | None = Field(default=None, alias="faceName")

    type: str = Field(description="The type line of the card.")
    types: list[str] = Field(default_factory=list)
    subtypes: list[str] = Field(default_factory=list)
    supertypes: list[str] = Field(default_factory=list)

    colors: list[str] = Field(default_factory=list)
    color_identity: list[str] = Field(default_factory=list, alias="colorIdentity")
    color_indicator: list[str] | None = Field(default=None, alias="colorIndicator")
    produced_mana: list[str] | None = Field(default=None, alias="producedMana")

    mana_cost: str | None = Field(default=None, alias="manaCost")
    text: str | None = Field(default=None)
    layout: str = Field(description="The type of card layout.")
    side: str | None = Field(default=None)

    power: str | None = Field(default=None)
    toughness: str | None = Field(default=None)
    loyalty: str | None = Field(default=None)

    keywords: list[str] | None = Field(default=None)
    identifiers: Identifiers = Field(default_factory=dict)  # type: ignore[assignment]
    is_funny: bool | None = Field(default=None, alias="isFunny")
    edhrec_saltiness: float | None = Field(default=None, alias="edhrecSaltiness")
    subsets: list[str] | None = Field(default=None)


class CardAtomicBase(CardBase):
    """Base for atomic (oracle-like) card properties."""

    converted_mana_cost: float | None = Field(default=None, alias="convertedManaCost")
    mana_value: float = Field(alias="manaValue")
    face_converted_mana_cost: float | None = Field(
        default=None, alias="faceConvertedManaCost"
    )
    face_mana_value: float | None = Field(default=None, alias="faceManaValue")

    defense: str | None = Field(default=None)
    hand: str | None = Field(default=None)
    life: str | None = Field(default=None)

    edhrec_rank: int | None = Field(default=None, alias="edhrecRank")
    foreign_data: list[ForeignData] | None = Field(default=None, alias="foreignData")

    legalities: Legalities = Field(default_factory=dict)  # type: ignore[assignment]
    leadership_skills: LeadershipSkills | None = Field(
        default=None, alias="leadershipSkills"
    )
    rulings: list[Rulings] | None = Field(default=None)

    has_alternative_deck_limit: bool | None = Field(
        default=None, alias="hasAlternativeDeckLimit"
    )
    is_reserved: bool | None = Field(default=None, alias="isReserved")
    is_game_changer: bool | None = Field(default=None, alias="isGameChanger")

    printings: list[str] | None = Field(default=None)
    purchase_urls: PurchaseUrls | None = Field(default=None, alias="purchaseUrls")
    related_cards: RelatedCards | None = Field(default=None, alias="relatedCards")


class CardPrintingBase(CardBase):
    """Base for printing-specific card properties."""

    uuid: str = Field(
        description="The universal unique identifier (v5) generated by MTGJSON."
    )
    set_code: str = Field(alias="setCode")
    number: str = Field(description="The collector number of the card.")

    artist: str | None = Field(default=None)
    artist_ids: list[str] | None = Field(default=None, alias="artistIds")
    border_color: str = Field(alias="borderColor")
    frame_version: str = Field(alias="frameVersion")
    frame_effects: list[str] | None = Field(default=None, alias="frameEffects")
    watermark: str | None = Field(default=None)
    signature: str | None = Field(default=None)
    security_stamp: str | None = Field(default=None, alias="securityStamp")

    flavor_text: str | None = Field(default=None, alias="flavorText")
    flavor_name: str | None = Field(default=None, alias="flavorName")
    face_flavor_name: str | None = Field(default=None, alias="faceFlavorName")

    original_text: str | None = Field(default=None, alias="originalText")
    original_type: str | None = Field(default=None, alias="originalType")
    printed_name: str | None = Field(default=None, alias="printedName")
    printed_text: str | None = Field(default=None, alias="printedText")
    printed_type: str | None = Field(default=None, alias="printedType")
    face_printed_name: str | None = Field(default=None, alias="facePrintedName")

    availability: list[str] = Field(default_factory=list)
    booster_types: list[str] | None = Field(default=None, alias="boosterTypes")
    finishes: list[str] = Field(default_factory=list)
    promo_types: list[str] | None = Field(default=None, alias="promoTypes")
    attraction_lights: list[int] | None = Field(default=None, alias="attractionLights")

    is_full_art: bool | None = Field(default=None, alias="isFullArt")
    is_online_only: bool | None = Field(default=None, alias="isOnlineOnly")
    is_oversized: bool | None = Field(default=None, alias="isOversized")
    is_promo: bool | None = Field(default=None, alias="isPromo")
    is_reprint: bool | None = Field(default=None, alias="isReprint")
    is_textless: bool | None = Field(default=None, alias="isTextless")

    other_face_ids: list[str] | None = Field(default=None, alias="otherFaceIds")
    card_parts: list[str] | None = Field(default=None, alias="cardParts")
    language: str = Field(default="English")
    source_products: list[str] | None = Field(default=None, alias="sourceProducts")


class CardPrintingFull(CardPrintingBase, CardAtomicBase):
    """Full printing with all atomic + printing fields."""

    rarity: str = Field(description="The card printing rarity.")
    duel_deck: str | None = Field(default=None, alias="duelDeck")

    is_rebalanced: bool | None = Field(default=None, alias="isRebalanced")
    original_printings: list[str] | None = Field(
        default=None, alias="originalPrintings"
    )
    rebalanced_printings: list[str] | None = Field(
        default=None, alias="rebalancedPrintings"
    )
    original_release_date: str | None = Field(default=None, alias="originalReleaseDate")

    is_alternative: bool | None = Field(default=None, alias="isAlternative")
    is_story_spotlight: bool | None = Field(default=None, alias="isStorySpotlight")
    is_timeshifted: bool | None = Field(default=None, alias="isTimeshifted")
    has_content_warning: bool | None = Field(default=None, alias="hasContentWarning")
    variations: list[str] | None = Field(default=None)


class CardAtomic(CardAtomicBase):
    """Oracle-like card data without printing-specific fields.

    Represents the canonical "oracle" version of a card — shared across
    all printings. Useful for deckbuilding tools, rules engines, and
    format legality checks where set/printing details are irrelevant.
    """

    first_printing: str | None = Field(default=None, alias="firstPrinting")


class CardSet(CardPrintingFull):
    """Card as it appears in a specific set printing.

    The primary card model for most SDK queries. Contains all oracle
    fields (name, text, colors, legalities) plus printing-specific
    fields (set code, collector number, artist, rarity, finishes).
    """

    source_products: SourceProducts | None = Field(  # type: ignore[assignment]
        default=None, alias="sourceProducts"
    )


class CardDeck(CardPrintingFull):
    """Card in a preconstructed deck, with count and foil/etched flags."""

    count: int = Field(description="The count of this card in the deck.")
    is_foil: bool | None = Field(default=None, alias="isFoil")
    is_etched: bool | None = Field(default=None, alias="isEtched")
    source_products: SourceProducts | None = Field(  # type: ignore[assignment]
        default=None, alias="sourceProducts"
    )
    original_release_date: str | None = Field(default=None, alias="originalReleaseDate")


class CardToken(CardPrintingBase):
    """Token card with orientation and reverse-related card references."""

    orientation: str | None = Field(default=None)
    reverse_related: list[str] | None = Field(default=None, alias="reverseRelated")
    related_cards: RelatedCards | None = Field(default=None, alias="relatedCards")
    edhrec_saltiness: float | None = Field(default=None, alias="edhrecSaltiness")
    source_products: SourceProducts | None = Field(  # type: ignore[assignment]
        default=None, alias="sourceProducts"
    )
    token_products: list[Any] | None = Field(default=None, alias="tokenProducts")


class CardSetDeck(BaseModel):
    """Minimal card reference in a deck (used in Set.decks)."""

    model_config = {"populate_by_name": True}

    count: int = Field(description="The count of this card in the deck.")
    is_foil: bool | None = Field(default=None, alias="isFoil")
    uuid: str = Field(
        description="The universal unique identifier (v5) generated by MTGJSON."
    )
