"""MTGJSON sealed product model (vendored, standalone)."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, model_validator

from .submodels import Identifiers, PurchaseUrls, SealedProductContents


class SealedProduct(BaseModel):
    """Sealed product (booster box, bundle, etc.)."""

    model_config = {"populate_by_name": True}

    uuid: str = Field(
        description="The universal unique identifier (v5) generated by MTGJSON."
    )
    name: str = Field(description="The name of the product.")
    category: str | None = Field(default=None)
    set_code: str | None = Field(default=None, alias="setCode")
    subtype: str | None = Field(default=None)
    language: str | None = None
    release_date: str | None = Field(default=None, alias="releaseDate")
    card_count: int | None = Field(default=None, alias="cardCount")
    product_size: int | None = Field(default=None, alias="productSize")
    contents: SealedProductContents | None = Field(default=None)
    identifiers: Identifiers = Field(default_factory=dict)  # type: ignore[assignment]
    purchase_urls: PurchaseUrls = Field(default_factory=dict, alias="purchaseUrls")  # type: ignore[assignment]

    @model_validator(mode="before")
    @classmethod
    def populate_finishes_from_foil(cls, data: Any) -> Any:
        """Populate finishes field from foil boolean for sealed product cards."""
        if isinstance(data, dict) and "contents" in data:
            contents = data["contents"]
            if isinstance(contents, dict) and "card" in contents:
                for card in contents["card"]:
                    if isinstance(card, dict) and "finishes" not in card:
                        card["finishes"] = ["foil"] if card.get("foil") else ["nonfoil"]
        return data
